# -------------------------------------------------------------------------
# Global settings for Jarvis assistant
# -------------------------------------------------------------------------
assistant:
  name: "Jarvis"                      # Assistant’s display name
  language: "en"                      # Default language
  wake_word: "hey jarvis"             # Wake-word phrase
  stt_engine: "vosk"                  # Options: 'vosk', 'whisper', etc.
  tts_engine: "pyttsx3"               # Options: 'pyttsx3', 'coqui', 'gtts'
  nlu_engine: "spacy"                 # Options: 'spacy'
  memory:
    short_term_capacity: 50           # Number of recent turns to keep in RAM
    long_term_db_path: "data/memory.db"
    vector_store_path: "data/embeddings.index"
  logging:
    level: "INFO"
    config_file: "config/logging.yaml"

# API keys or credentials (e.g., for Google Calendar, weather, etc.)
api_keys:
  google_calendar: "YOUR_GOOGLE_CALENDAR_API_KEY"
  openai: "YOUR_OPENAI_API_KEY"        # if using Whisper or embeddings
  weather: "YOUR_WEATHER_API_KEY"

# Home Assistant (smart home) connection
home_assistant:
  host: "http://localhost:8123"
  access_token: "YOUR_LONG_LIVED_TOKEN"

logging:
  version: 1
  formatters:
    detailed:
      format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: detailed
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: detailed
      filename: "logs/jarvis.log"
  root:
    level: INFO
    handlers: [console, file]
